export enum TipoEvento {
  PESSOAL = 'PESSOAL',
  TRABALHO = 'TRABALHO',
  REUNIAO = 'REUNIAO',
  VIAGEM = 'VIAGEM',
  SAUDE = 'SAUDE',
  ESTUDO = 'ESTUDO',
  FERIAS = 'FERIAS',
  APRESENTACAO = 'APRESENTACAO',
  CONFERENCIA = 'CONFERENCIA',
  REUNIAO_INTERNA = 'REUNIAO_INTERNA',
  EVENTO_EXTERNO = 'EVENTO_EXTERNO',
  LEMBRETE = 'LEMBRETE',
}
