export enum Setor {
    CONTABIL = 'CONTABIL',
    FISCAL = 'FISCAL',
    PESSOAL = 'PESSOAL',
    PARALEGAL = 'PARALEGAL',
    FINANCEIRO = 'FINANCEIRO',
    JURIDICO = 'JURIDICO',
    ADMINISTRATIVO = 'ADMINISTRATIVO',
    RH = "RH",
    SUPORTE_TI = 'SUPORTE_TI',
    ESTAGIARIO = 'ESTAGIARIO',
    OUTRO = 'OUTRO'
}
