export enum Setor {
    CONTABIL = 'CONTABIL',
    FISCAL = 'FISCAL',
    PESSOAL = 'PESSOAL',
    PARALEGAL = 'PARALEGAL',
    FINANCEIRO = 'FINANCEIRO',
    JURIDICO = 'JURIDICO',
    ESTAGIARIO = 'ESTAGIARIO',
    OUTRO = 'OUTRO'
}
