export enum PorteEmpresa {
  MEI = 'MEI',
  MICRO_EMPRESA = 'MICRO_EMPRESA',
  EMPRESA_PEQUENO_PORTE = 'EMPRESA_PEQUENO_PORTE',
  EMPRESA_MEDIO_PORTE = 'EMPRESA_MEDIO_PORTE',
  EMPRESA_GRANDE_PORTE = 'EMPRESA_GRANDE_PORTE',
}
